### PR TITLE
Add support for Laravel 5.8

### PR DESCRIPTION
**Pull request by matsava**
Couldn't find any arr_* helpers etc. so this should be a safe upgrade.

I also removed the "linting" option in StyleCI since it has been deprecated a long time ago :)

### CODE REVIEW

**Comment by etiennemarais** [comment]
Thank you 🚀

**Comment by matsava** [comment]
Hey @etiennemarais, the last version tagged for L.5.8 has not been updated on packagist. 😕 Can you please check it out?

**Comment by etiennemarais** [comment]
I don't own the packagist parts unfortunately. That should update automatically afaik. @themsaid Please can you kick the refresh token on packagist please? 😂 The [latest release](https://github.com/laravel-notification-channels/clickatell/releases/tag/0.1.2) is not showing up.

**Comment by etiennemarais** [comment]
@chrysanthos Seems like the packagist has updated 🎉 Thanks

**Pull request merged**
